# -*- coding: utf-8 -*-
"""Italian Idioms - Structured Data (with Chinese translations)"""

IDIOMS = [
    {
        "id": 1,
        "idiom": "In bocca al lupo!",
        "category": "Auguri / Incoraggiamento",
        "meaning_cn": "祝你好运！/ 加油！",
        "meaning_it": "Espressione di augurio per un'impresa difficile.",
        "usage_cn": "用于考试、面试、表演等重大场合前祝福他人。回答要说「Crepi!」或「Crepi il lupo!」",
        "examples": [
            ("A", "Domani ho un'audizione per entrare nel conservatorio.", "明天我有一个音乐学院的面试。"),
            ("B", "In bocca al lupo!", "祝你好运！"),
            ("A", "Grazie, crepi!", "谢谢，借你吉言！"),
        ],
        "cultural_cn": "直译「到狼嘴里去！」源于猎人传统，认为直接说「好运」会招来厄运，所以用反语祝福。回答「Crepi (il lupo)!」意为「狼死掉！」，形成完整的祝福对话。",
        "exercise_q": [
            {'question': '「In bocca al lupo!」的正确回答是？', 'options': ['Grazie mille!', 'Buona giornata!', 'Crepi!', 'Prego!'], 'answer': 'C) Crepi!'},
            {'question': '完成对话：A: Devo fare un esame difficile. B: ________________! A: Grazie, ________!', 'fill': ['In bocca al lupo', 'crepi']},
        ],
        "english_eq": "Break a leg!",
        "meaning_it_cn": "对一项困难的事情表达祝福的表达方式。",
    },
    {
        "id": 2,
        "idiom": "Da che pulpito!",
        "category": "Rimprovero / Ironia",
        "meaning_cn": "你也好意思说！/ 你还有脸说！",
        "meaning_it": "Critica ironica a chi rimprovera gli altri per difetti che ha anche lui.",
        "usage_cn": "当某人批评别人时，他自己也有同样的毛病。用「Parli da che pulpito!」更完整。",
        "examples": [
            ("A", "Non bisogna mai arrivare in ritardo.", "绝对不能迟到。"),
            ("B", "Parli da che pulpito! Anche ieri sei arrivato con mezz'ora di ritardo!", "你也好意思说！昨天你就迟到了半小时！"),
            ("A2", "Fumi troppo, dovresti smettere.", "你烟抽得太多了，应该戒掉。"),
            ("B2", "Da che pulpito! Sei tu che fumi più di me!", "你还有脸说！你抽得比我还多！"),
        ],
        "cultural_cn": "「Pulpito」是教堂的讲道坛。这句话源于教堂——一个从讲道坛上布道的人自己不遵守教义。相当于英语的「Look who's talking!」或「You're one to talk!」",
        "exercise_q": [
            {'question': '「Da che pulpito!」的最佳对应是？', 'options': ['Complimenti, bravissimo!', 'Anche tu fai la stessa cosa!', 'Andiamo via adesso.', 'Non so cosa dire.'], 'answer': 'B) Anche tu fai la stessa cosa!'},
            {'question': '完成句子：A: Non bisogna mai dire bugie. B: ________________________! Anche tu mi hai mentito ieri.', 'fill': ['Parli da che pulpito']},
        ],
        "english_eq": "Look who's talking! / You're one to talk!",
        "meaning_it_cn": "对指责别人也有同样毛病的人进行讽刺性的批评。",
    },
    {
        "id": 3,
        "idiom": "Non tutte le ciambelle riescono col buco.",
        "category": "Consolazione / Realismo",
        "meaning_cn": "人生不如意事十之八九。/ 事与愿违。",
        "meaning_it": "Non tutto nella vita riesce perfetto come sperato.",
        "usage_cn": "当事情没按计划进行时，用来安慰人或表达现实中不完美是正常的。",
        "examples": [
            ("A", "Non sono riuscita a passare l'esame, sono distrutta.", "我没能通过考试，我崩溃了。"),
            ("B", "Non ti preoccupare, non tutte le ciambelle riescono col buco.", "别担心，人生不如意事十之八九。"),
            ("A2", "Il viaggio è stato un disastro, niente è andato come speravo.", "这次旅行简直是灾难，没有一件事如我所愿。"),
            ("B2", "Eh, non tutte le ciambelle riescono col buco. Magari la prossima volta sarà migliore.", "唉，人生不可能事事完美。也许下次会更好。"),
        ],
        "cultural_cn": "「Ciambella col buco」是意大利经典的环状甜甜圈。如果中间没有洞，就不是完美的甜甜圈。这个比喻告诉我们：有时候事情就是不会完美如预期，但这很正常。",
        "exercise_q": [
            {'question': '「Non tutte le ciambelle riescono col buco」的意思是？', 'options': ['I dolci non piacciono a tutti.', 'Bisogna sempre cucinare con attenzione.', 'Nella vita non tutto è perfetto.', 'Le ciambelle con il buco sono più sane.'], 'answer': 'C) Nella vita non tutto è perfetto.'},
            {'question': "完成句子：Non preoccuparti per l'errore, ________________________________.", 'fill': ['non tutte le ciambelle riescono col buco']},
        ],
        "english_eq": "You can't always get what you want.",
        "meaning_it_cn": "生活中不是每件事都能如愿以偿地完美。",
    },
    {
        "id": 4,
        "idiom": "Avere le mani bucate",
        "category": "Difetto / Economia",
        "meaning_cn": "花钱如流水 / 存不住钱",
        "meaning_it": "Non riuscire a conservare i soldi, spenderli subito.",
        "usage_cn": "描述一个人一有钱就花光、存不住钱的挥霍习惯。",
        "examples": [
            ("A", "Come mai non hai ancora messo da parte nemmeno un euro dopo il bonus?", "拿了奖金你怎么一分钱都没存下来？"),
            ("B", "Eh, ho le mani bucate... appena ricevo i soldi, li spendo!", "唉，我花钱如流水……一拿到钱我就花掉了！"),
        ],
        "cultural_cn": "「Mani = 手」「bucate = 有洞的」。字面意思是「手上有洞」，钱从洞里漏出去了。相当于英语的「money burns a hole in one's pocket」。",
        "exercise_q": [
            {'question': '「Avere le mani bucate」的意思是？', 'options': ['Avere difficoltà a tenere oggetti in mano', 'Non riuscire a conservare i soldi, spendendoli subito', 'Avere molta forza nelle mani', 'Essere molto abile nel lavorare con le mani'], 'answer': 'B) Non riuscire a conservare i soldi, spendendoli subito'},
            {'question': 'Anche se prende uno stipendio alto, Gianni ______________________________: finisce sempre i soldi prima della fine del mese.', 'fill': ['ha le mani bucate']},
        ],
        "english_eq": "Money burns a hole in one's pocket",
        "meaning_it_cn": "存不住钱，一拿到就花掉。",
    },
    {
        "id": 5,
        "idiom": "Prendere due piccioni con una fava.",
        "category": "Efficienza / Strategia",
        "meaning_cn": "一箭双雕 / 一举两得",
        "meaning_it": "Riuscire a ottenere due risultati con un'unica azione.",
        "usage_cn": "用一个行动达到两个目的时使用。",
        "examples": [
            ("A", "Come mai vai a lavorare in bicicletta?", "你为什么骑自行车去上班？"),
            ("B", "Perché così prendo due piccioni con una fava: faccio movimento e risparmio sulla benzina.", "因为这样一举两得：既锻炼了身体，又省了油钱。"),
        ],
        "cultural_cn": "「Piccione = 鸽子」「fava = 蚕豆」。用一颗蚕豆捉两只鸽子，即一举两得。相当于英语的「kill two birds with one stone」。",
        "exercise_q": [
            {'question': '「Prendere due piccioni con una fava」的意思是？', 'options': ['Catturare due animali con le mani', "Riuscire a ottenere due risultati con un'unica azione", 'Mangiare legumi con gli amici', 'Viaggiare con poco denaro'], 'answer': "B) Riuscire a ottenere due risultati con un'unica azione"},
            {'question': 'Lavorando da remoto, puoi _________________________________: risparmi tempo e vivi più vicino alla natura.', 'fill': ['prendere due piccioni con una fava']},
        ],
        "english_eq": "Kill two birds with one stone",
        "meaning_it_cn": "通过一个行动获得两个结果。",
    },
    {
        "id": 6,
        "idiom": "Patti chiari, amicizia lunga.",
        "category": "Relazioni / Affari",
        "meaning_cn": "亲兄弟明算账。/ 先小人后君子。",
        "meaning_it": "Definire bene le regole per mantenere buone relazioni.",
        "usage_cn": "在合作或交易前强调明确规则的重要性，避免日后纠纷。",
        "examples": [
            ("A", "Prima di iniziare questo lavoro insieme, dobbiamo parlare dei ruoli.", "在开始这项合作之前，我们需要谈谈分工。"),
            ("B", "Esatto, patti chiari, amicizia lunga!", "没错，先小人后君子嘛！"),
        ],
        "cultural_cn": "「Patti = 约定/协议」「chiari = 清晰的」「amicizia = 友谊」「lunga = 长久的」。字面意思：约定清楚，友谊长久。",
        "exercise_q": [
            {'question': '「Patti chiari, amicizia lunga」的意思是？', 'options': ['Bisogna firmare contratti lunghi per essere amici', 'Definire bene le regole e le aspettative per mantenere buone relazioni', 'Solo gli amici possono fare accordi', 'Le amicizie durano solo se si litiga spesso'], 'answer': 'B) Definire bene le regole e le aspettative per mantenere buone relazioni'},
            {'question': 'Prima di iniziare il progetto con il team esterno, il capo ci ha ricordato:________________________________________ Così nessuno si confonde.', 'fill': ['patti chiari, amicizia lunga']},
        ],
        "english_eq": "Clear agreements make for lasting friendships",
        "meaning_it_cn": "明确规则和期望，以维持良好关系。",
    },
    {
        "id": 7,
        "idiom": "Chi va piano, va sano e va lontano.",
        "category": "Saggezza / Pazienza",
        "meaning_cn": "欲速则不达。/ 稳扎稳打，行稳致远。",
        "meaning_it": "Procedere con calma e costanza porta risultati duraturi.",
        "usage_cn": "劝人不要急躁，慢工出细活，稳步前进才能走得更远。",
        "examples": [
            ("A", "Voglio finire il progetto in una settimana, anche se significa lavorare notte e giorno.", "我想在一周内完成这个项目，即使要夜以继日地工作。"),
            ("B", "Ricorda, chi va piano, va sano e va lontano. Meglio farlo bene che bruciarsi.", "记住，欲速则不达。做好比累垮更重要。"),
        ],
        "cultural_cn": "「Chi = 谁」「va = 走」「piano = 慢地」「sano = 健康地」「lontano = 远方」。三个词押韵（piano/sano/lontano），朗朗上口。相当于英语的「Slow and steady wins the race」。",
        "exercise_q": [
            {'question': '「Chi va piano, va sano e va lontano」的意思是？', 'options': ['Chi cammina lentamente vive più a lungo', 'Meglio procedere con calma e costanza per ottenere risultati duraturi e senza rischi', 'Solo i pigri riescono a raggiungere obiettivi lontani', 'Camminare veloce fa male alla salute'], 'answer': 'B) Meglio procedere con calma e costanza per ottenere risultati duraturi e senza rischi'},
            {'question': 'Se vuoi imparare a suonare il pianoforte bene, ricorda: __________________________________________________. Così migliorerai passo dopo passo.', 'fill': ['chi va piano, va sano e va lontano']},
        ],
        "english_eq": "Slow and steady wins the race",
        "meaning_it_cn": "从容而稳定地前进，才能获得持久的结果且没有风险。",
    },
    {
        "id": 8,
        "idiom": "Tra il dire e il fare c'è di mezzo il mare.",
        "category": "Saggezza / Azione",
        "meaning_cn": "说起来容易做起来难。/ 言行之间隔着一片海。",
        "meaning_it": "Grandi difficoltà nel passare dalle parole ai fatti.",
        "usage_cn": "批评光说不做的人，或提醒别人实际行动比口头承诺困难得多。",
        "examples": [
            ("A", "Ho deciso di iniziare una dieta e correre ogni mattina...", "我决定开始节食，每天早上跑步……"),
            ("B", "Sì, ma tra il dire e il fare c'è di mezzo il mare. Fammi sapere quando cominci sul serio!", "是啊，说起来容易做起来难。你真开始的时候告诉我吧！"),
        ],
        "cultural_cn": "「tra...e... = 在...之间」「c'è di mezzo = 有...在中间」「mare = 海」。语言和行动之间的差距就像海洋一样广阔。",
        "exercise_q": [
            {'question': "「Tra il dire e il fare c'è di mezzo il mare」的意思是？", 'options': ['Parlare è più difficile che agire', 'Ci sono grandi difficoltà nel passare dalle parole ai fatti', 'Il mare separa le persone che parlano tra loro', 'Dire bugie crea distanze enormi'], 'answer': 'B) Ci sono grandi difficoltà nel passare dalle parole ai fatti'},
            {'question': "Hai promesso di scrivere il libro entro l'anno, ma __________________________________________ : inizia oggi stesso!", 'fill': ["tra il dire e il fare c'è di mezzo il mare"]},
        ],
        "english_eq": "Easier said than done / There's many a slip 'twixt cup and lip",
        "meaning_it_cn": "从言语到行动之间存在巨大的困难。",
    },
    {
        "id": 9,
        "idiom": "Chi cerca trova.",
        "category": "Incoraggiamento / Ottimismo",
        "meaning_cn": "有志者事竟成。/ 功夫不负有心人。",
        "meaning_it": "Se cerchi con impegno, puoi trovare ciò che ti serve.",
        "usage_cn": "鼓励别人坚持寻找、不放弃。",
        "examples": [
            ("A", "Non riesco a trovare un modo per migliorare il mio inglese...", "我找不到提高英语水平的方法……"),
            ("B", "Continua a cercare, perché chi cerca trova. Prova podcast o scambi linguistici.", "继续找，因为功夫不负有心人。试试播客或语言交换吧。"),
        ],
        "cultural_cn": "「chi = 谁」「cerca = 寻找」「trova = 找到」。这是一个简洁有力的三词谚语，鼓励人不放弃。相当于英语的「Seek and you shall find」。",
        "exercise_q": [
            {'question': '「Chi cerca trova」的意思是？', 'options': ['Solo i forti riescono nelle ricerche', 'Se cerchi con impegno, puoi trovare ciò che ti serve o desideri', 'La ricerca porta sempre più dubbi', 'Trovare qualcosa è impossibile senza soldi'], 'answer': 'B) Se cerchi con impegno, puoi trovare ciò che ti serve o desideri'},
            {'question': '______________________________ : bastava consultare gli archivi digitali invece di cercare solo nei libri cartacei.', 'fill': ['Chi cerca trova']},
        ],
        "english_eq": "Seek and you shall find",
        "meaning_it_cn": "如果你用心寻找，就能找到你需要或想要的东西。",
    },
    {
        "id": 10,
        "idiom": "Sbagliando s'impara.",
        "category": "Incoraggiamento / Apprendimento",
        "meaning_cn": "失败是成功之母。/ 吃一堑，长一智。",
        "meaning_it": "Si acquisisce conoscenza attraverso gli errori commessi.",
        "usage_cn": "安慰犯错的人，告诉他们错误是学习的一部分。",
        "examples": [
            ("A", "Ho sbagliato il discorso in pubblico e mi sono sentito umiliato...", "我在公开演讲中出错了，感到很难堪……"),
            ("B", "Non preoccuparti, sbagliando s'impara. Ora sai cosa migliorare per la prossima volta.", "别担心，失败是成功之母。现在你知道下次怎么改进了。"),
        ],
        "cultural_cn": "「Sbagliando = sbagliare的副动词/犯错」「s'impara = si impara的缩写/学习」。犯错中学习，这也是意大利教育理念的一部分。",
        "exercise_q": [
            {'question': "「Sbagliando s'impara」的意思是？", 'options': ['Gli errori vanno ignorati', 'Si può acquisire conoscenza attraverso gli errori commessi', 'Bisogna evitare di provare cose nuove', 'Commettere errori rende incapaci'], 'answer': 'B) Si può acquisire conoscenza attraverso gli errori commessi'},
            {'question': 'Non scoraggiarti se la tua ricetta non è venuta perfetta: ______________________________ . Provaci ancora e vedrai miglioramenti.', 'fill': ["sbagliando s'impara"]},
        ],
        "english_eq": "You learn from your mistakes / Practice makes perfect",
        "meaning_it_cn": "通过犯错误来获取知识。",
    },
    {
        "id": 11,
        "idiom": "Chi ben comincia è a metà dell'opera.",
        "category": "Saggezza / Organizzazione",
        "meaning_cn": "良好的开端是成功的一半。",
        "meaning_it": "Una buona preparazione iniziale facilita il completamento del compito.",
        "usage_cn": "强调开始做计划、准备充分的重要性。",
        "examples": [
            ("A", "Sto per iniziare un nuovo corso di fotografia, ma non so da dove cominciare...", "我即将开始一门新的摄影课程，但不知道从何开始……"),
            ("B", "Ricorda, chi ben comincia è a metà dell'opera. Prepara il materiale e studia le basi con calma.", "记住，良好的开端是成功的一半。慢慢准备材料，打好基础。"),
        ],
        "cultural_cn": "「chi ben comincia = 谁开始得好」「è a metà dell'opera = 已经在作品的一半了」。相当于英语的「Well begun is half done」。",
        "exercise_q": [
            {'question': "「Chi ben comincia è a metà dell'opera」的意思是？", 'options': ['Iniziare bene significa aver già terminato il lavoro', 'Una buona preparazione iniziale facilita molto il completamento del compito', 'È meglio non iniziare affatto che iniziare male', "L'inizio non influenza il risultato finale"], 'answer': 'B) Una buona preparazione iniziale facilita molto il completamento del compito'},
            {'question': 'Prima di lanciare il tuo business, pianifica con attenzione: __________________________________________________. Così aumenti le probabilità di successo.', 'fill': ["chi ben comincia è a metà dell'opera"]},
        ],
        "english_eq": "Well begun is half done",
        "meaning_it_cn": "良好的初始准备能大大促进任务的完成。",
    },
    {
        "id": 12,
        "idiom": "A caval donato non si guarda in bocca.",
        "category": "Gratitudine / Relazioni",
        "meaning_cn": "受赠之物，勿挑剔。/ 别挑别人送的礼。",
        "meaning_it": "Non si devono criticare i doni ricevuti.",
        "usage_cn": "收到礼物时，即使不尽如人意也不该挑剔批评。",
        "examples": [
            ("A", "Grazie per il computer usato, ma ha qualche problema nello schermo...", "谢谢你的旧电脑，但屏幕有点问题……"),
            ("B", "Dai, a caval donato non si guarda in bocca. È comunque un grande aiuto.", "得了，别挑剔了。这总归是个很大的帮助。"),
        ],
        "cultural_cn": "「caval = cavallo的缩写/马」「donato = 赠送的」「guardare in bocca = 看马的牙齿（判断年龄）」。古时买马会看牙齿判断年龄，但如果是别人送的礼物，就不该这样做了。相当于英语的「Don't look a gift horse in the mouth」。",
        "exercise_q": [
            {'question': '「A caval donato non si guarda in bocca」的意思是？', 'options': ['I regali vanno sempre restituiti', 'Non si devono criticare i doni ricevuti', 'I cavalli regalati sono sempre perfetti', 'Guardare nella bocca di un cavallo porta sfortuna'], 'answer': 'B) Non si devono criticare i doni ricevuti'},
            {'question': "Hai ricevuto un vestito usato dalla nonna: _______________________________________________ , è un pensiero d'amore.", 'fill': ['a caval donato non si guarda in bocca']},
        ],
        "english_eq": "Don't look a gift horse in the mouth",
        "meaning_it_cn": "不应批评收到的礼物。",
    },
    {
        "id": 13,
        "idiom": "Il troppo stroppia.",
        "category": "Saggezza / Moderazione",
        "meaning_cn": "过犹不及。/ 凡事有度。",
        "meaning_it": "Un eccesso può rovinare l'effetto positivo di qualcosa.",
        "usage_cn": "提醒人不要过度，任何事情过了头都会产生负面效果。",
        "examples": [
            ("A", "Studio dieci ore al giorno da una settimana, ma ora sono esausto e non ricordo più nulla...", "我已经连续一周每天学习十个小时，但现在筋疲力尽，什么都记不住了……"),
            ("B", "Hai visto? Il troppo stroppia. Riposati un po', altrimenti non assorbi più niente.", "看到了吧？过犹不及。休息一下，否则你什么都吸收不了。"),
        ],
        "cultural_cn": "「troppo = 太多」「stroppia = 弄坏/损坏（古意大利语）」。这个古老的谚语强调了意大利文化中的平衡理念，与「Chi va piano, va sano e va lontano」形成对照。",
        "exercise_q": [
            {'question': '「Il troppo stroppia」的意思是？', 'options': ['Tutto ciò che è abbondante è sempre positivo', "Un eccesso può rovinare l'effetto positivo di qualcosa", 'Bisogna evitare di fare qualsiasi cosa', 'Lo sforzo fisico non deve mai essere misurato'], 'answer': "B) Un eccesso può rovinare l'effetto positivo di qualcosa"},
            {'question': 'Lavorare fino a tardi ogni sera sembra produttivo, ma ______________________________ : la mancanza di sonno riduce la produttività.', 'fill': ['il troppo stroppia']},
        ],
        "english_eq": "Too much of a good thing / Enough is enough",
        "meaning_it_cn": "过度会破坏某事的积极效果。",
    },
    {
        "id": 14,
        "idiom": "Meglio tardi che mai.",
        "category": "Incoraggiamento / Ottimismo",
        "meaning_cn": "迟做总比不做好。",
        "meaning_it": "Far qualcosa in ritardo è preferibile a non farla affatto.",
        "usage_cn": "鼓励那些觉得已经太晚而犹豫不决的人。",
        "examples": [
            ("A", "Avrei voluto iniziare a studiare il pianoforte da giovane, ma ora ho quasi cinquant'anni...", "我本该年轻时就开始学钢琴，但现在都快五十了……"),
            ("B", "Meglio tardi che mai! Puoi cominciare adesso e scoprire quanto ti piace.", "迟做总比不做好！你现在就可以开始，看看你有多喜欢。"),
        ],
        "cultural_cn": "「meglio = 更好」「tardi = 晚」「che = 比...」「mai = 从不」。相当于英语的「Better late than never」, 这是一个跨文化的普遍智慧。",
        "exercise_q": [
            {'question': '「Meglio tardi che mai」的意思是？', 'options': ['È meglio non fare nulla piuttosto che farlo in ritardo', 'Far qualcosa in ritardo è comunque preferibile a non farla affatto', 'Tardare è sempre un errore grave', "Mai iniziare un'attività se non si è giovani"], 'answer': 'B) Far qualcosa in ritardo è comunque preferibile a non farla affatto'},
            {'question': 'Non hai ancora iniziato quel corso online? Non importa: ______________________________ , iscriviti oggi stesso.', 'fill': ['meglio tardi che mai']},
        ],
        "english_eq": "Better late than never",
        "meaning_it_cn": "晚做某事总比完全不做好。",
    },
    {
        "id": 15,
        "idiom": "Chi dorme non piglia pesci.",
        "category": "Incoraggiamento / Azione",
        "meaning_cn": "早起的鸟儿有虫吃。/ 坐失良机。",
        "meaning_it": "Solo chi è sveglio e agisce può ottenere risultati.",
        "usage_cn": "劝人不要懒惰，要主动出击抓住机会。",
        "examples": [
            ("A", "Aspetto che arrivi un'offerta di lavoro perfetta senza fare domande...", "我在等一份完美的工作机会送上门来，没有投任何简历……"),
            ("B", "Ricordati, chi dorme non piglia pesci. Invia il CV e partecipa ai colloqui!", "记住，早起的鸟儿有虫吃。快发简历，参加面试吧！"),
        ],
        "cultural_cn": "「chi dorme = 睡觉的人」「piglier = piglia（托斯卡纳方言）= 捕捉」「pesci = 鱼」。睡着的渔夫捕不到鱼。相当于英语的「The early bird catches the worm」或「You snooze, you lose」。",
        "exercise_q": [
            {'question': '「Chi dorme non piglia pesci」的意思是？', 'options': ['Dormire troppo fa male alla salute', 'Solo chi è sveglio e agisce può ottenere risultati', 'I pescatori devono restare svegli tutta la notte', 'Non bisogna mai mangiare pesce'], 'answer': 'B) Solo chi è sveglio e agisce può ottenere risultati'},
            {'question': 'Se vuoi trovare nuove opportunità, ricorda: ________________________________________ . Inizia subito a muoverti.', 'fill': ['chi dorme non piglia pesci']},
        ],
        "english_eq": "The early bird catches the worm / You snooze, you lose",
        "meaning_it_cn": "只有清醒并行动的人才能获得成果。",
    },
    {
        "id": 16,
        "idiom": "Roma non fu fatta in un giorno.",
        "category": "Pazienza / Perseveranza",
        "meaning_cn": "罗马不是一天建成的。/ 冰冻三尺非一日之寒。",
        "meaning_it": "Le grandi imprese richiedono tempo e costanza.",
        "usage_cn": "当进展缓慢时，提醒人要有耐心，伟大事业需要时间。",
        "examples": [
            ("A", "Studio l'italiano da sei mesi ma faccio ancora errori grammaticali...", "我学了六个月意大利语，但语法还是出错……"),
            ("B", "Pazienza! Ricorda che Roma non fu fatta in un giorno. Continua a esercitarti.", "耐心点！记住罗马不是一天建成的。继续练习吧。"),
        ],
        "cultural_cn": "「Roma = 罗马」「non fu fatta = 不是被建造的（passato remoto）」「in un giorno = 在一天内」。这个世界上最著名的谚语之一，提醒人们伟大需要时间。",
        "exercise_q": [
            {'question': '「Roma non fu fatta in un giorno」的意思是？', 'options': ['La città di Roma è molto antica', 'Le grandi imprese richiedono tempo e costanza, non succedono improvvisamente', 'È inutile provare a costruire qualcosa di grande', 'Le cose fatte in fretta sono le migliori'], 'answer': 'B) Le grandi imprese richiedono tempo e costanza, non succedono improvvisamente'},
            {'question': 'Non preoccuparti se non sei ancora fluente dopo un anno di studio. _______________________________________ : devi solo continuare a leggere e ascoltare.', 'fill': ['Roma non fu fatta in un giorno']},
        ],
        "english_eq": "Rome wasn't built in a day",
        "meaning_it_cn": "伟大的事业需要时间和坚持，不会一蹴而就。",
    },
    {
        "id": 17,
        "idiom": "Chi troppo vuole nulla stringe.",
        "category": "Saggezza / Moderazione",
        "meaning_cn": "贪多嚼不烂。/ 样样通样样松。",
        "meaning_it": "Volere troppe cose contemporaneamente porta a non ottenere nulla.",
        "usage_cn": "劝人专注，不要贪心地追求太多目标。",
        "examples": [
            ("A", "Ho deciso di studiare italiano, spagnolo e francese contemporaneamente per diventare poliglotta in un anno!", "我决定同时学意大利语、西班牙语和法语，想一年内成为多语者！"),
            ("B", "Calma! Ricorda che chi troppo vuole nulla stringe. Meglio concentrarsi su una lingua alla volta.", "冷静！记住贪多嚼不烂。最好一次专注于一门语言。"),
        ],
        "cultural_cn": "「chi troppo vuole = 想要太多的人」「nulla stringe = 什么都抓不住（stringere = 抓住）」。相当于英语的「Grasp all, lose all」或「Don't bite off more than you can chew」。",
        "exercise_q": [
            {'question': '「Chi troppo vuole nulla stringe」的意思是？', 'options': ['Chi ha grandi ambizioni ottiene sempre tutto', 'Volere troppe cose contemporaneamente porta a non ottenere nulla', 'Bisogna stringere forte le mani per avere successo', 'Chi è avaro perde tutto'], 'answer': 'B) Volere troppe cose contemporaneamente porta a non ottenere nulla'},
            {'question': 'Non cercare di leggere cinque libri in una settimana, altrimenti _________________________________________________ . Concentrati su uno solo.', 'fill': ['chi troppo vuole nulla stringe']},
        ],
        "english_eq": "Grasp all, lose all / Don't bite off more than you can chew",
        "meaning_it_cn": "同时想要太多东西会导致什么都得不到。",
    },
    {
        "id": 18,
        "idiom": "Tutte le strade portano a Roma.",
        "category": "Saggezza / Strategia",
        "meaning_cn": "条条大路通罗马。/ 殊途同归。",
        "meaning_it": "Esistono molti modi diversi per raggiungere lo stesso obiettivo.",
        "usage_cn": "告诉别人不必拘泥于一种方法，多种途径都可以达到同样的目的。",
        "examples": [
            ("A", "Non capisco perché studi l'italiano con i film invece che con la grammatica tradizionale...", "我不明白你为什么通过电影而非传统语法书学意大利语……"),
            ("B", "Pazienza! Tutte le strade portano a Roma. Alla fine parlerò bene comunque.", "耐心点！条条大路通罗马。最终我都能说好。"),
        ],
        "cultural_cn": "「tutte le strade = 所有的路」「portano a Roma = 通向罗马」。古罗马帝国修建了四通八达的道路网，一切都通向帝国的中心——罗马。这句话已经成为世界性的谚语。",
        "exercise_q": [
            {'question': '「Tutte le strade portano a Roma」的意思是？', 'options': ["Roma è l'unica città che conta", 'Esistono molti modi diversi per raggiungere lo stesso obiettivo', "Viaggiare è l'unico modo per imparare", 'Le strade antiche sono le migliori'], 'answer': 'B) Esistono molti modi diversi per raggiungere lo stesso obiettivo'},
            {'question': "Non importa se usi l'autobus o il treno per arrivare lì, __________________________________________________ . L'importante è arrivare puntuali.", 'fill': ['tutte le strade portano a Roma']},
        ],
        "english_eq": "All roads lead to Rome",
        "meaning_it_cn": "有很多不同的方式可以达到同一个目标。",
    },
    {
        "id": 19,
        "idiom": "Chi si contenta gode.",
        "category": "Saggezza / Felicità",
        "meaning_cn": "知足常乐。",
        "meaning_it": "Essere soddisfatti di ciò che si ha porta alla vera felicità.",
        "usage_cn": "劝人珍惜当下拥有，不要总是羡慕他人。",
        "examples": [
            ("A", "Guarda la macchina nuova di Marco, la mia è così vecchia e piccola...", "看看马克的新车，我的又旧又小……"),
            ("B", "Non fare così, chi si contenta gode. La tua macchina funziona bene e ti porta ovunque.", "别这样，知足常乐。你的车性能很好，能带你去任何地方。"),
        ],
        "cultural_cn": "「chi si contenta = 满足的人」「gode = 享受/快乐（godere）」。这是一个典型的意大利生活哲学——享受生活中的小确幸。",
        "exercise_q": [
            {'question': '「Chi si contenta gode」的意思是？', 'options': ['Chi ha molti soldi è sempre felice', 'Essere soddisfatti di ciò che si ha porta alla vera felicità', 'Bisogna sempre chiedere di più per essere contenti', 'Chi ride per primo ride meglio'], 'answer': 'B) Essere soddisfatti di ciò che si ha porta alla vera felicità'},
            {'question': "Non preoccuparti se non hai l'ultimo modello di telefono. Ricorda: _________________________________________ . Quello che hai funziona benissimo.", 'fill': ['chi si contenta gode']},
        ],
        "english_eq": "A contented mind is a perpetual feast",
        "meaning_it_cn": "对自己拥有的感到满足能带来真正的幸福。",
    },
    {
        "id": 20,
        "idiom": "Al bisogno si conosce l'amico.",
        "category": "Relazioni / Amicizia",
        "meaning_cn": "患难见真情。",
        "meaning_it": "Solo nelle difficoltà si capisce chi è un vero amico.",
        "usage_cn": "在困难时刻才真正认识到谁是真正的朋友。",
        "examples": [
            ("A", "Ho perso il lavoro e solo Marco mi ha offerto aiuto e supporto...", "我失业了，只有马克给了我帮助和支持……"),
            ("B", "Vedi? Al bisogno si conosce l'amico. Gli altri erano solo compagni di divertimento.", "看到了吧？患难见真情。其他人只是酒肉朋友。"),
        ],
        "cultural_cn": "「al bisogno = 在需要时」「si conosce = 认识到」「l'amico = 朋友」。相当于英语的「A friend in need is a friend indeed」。",
        "exercise_q": [
            {'question': "「Al bisogno si conosce l'amico」的意思是？", 'options': ['Gli amici si incontrano sempre nei momenti di bisogno', 'Solo nelle difficoltà si capisce chi è un vero amico', 'Bisogna chiedere aiuto a tutti gli amici', 'Gli amici scompaiono quando serve aiuto'], 'answer': 'B) Solo nelle difficoltà si capisce chi è un vero amico'},
            {'question': 'Non fidarti di chi ti lascia solo ora che sei in difficoltà. Ricorda: _________________________________________________ . Valuta bene le tue amicizie.', 'fill': ["al bisogno si conosce l'amico"]},
        ],
        "english_eq": "A friend in need is a friend indeed",
        "meaning_it_cn": "只有在困难中才能认清谁是真正的朋友。",
    },
    {
        "id": 21,
        "idiom": "Piangere sul latte versato.",
        "category": "Consolazione / Realismo",
        "meaning_cn": "覆水难收。/ 为打翻的牛奶哭泣。",
        "meaning_it": "È inutile disperarsi per qualcosa che non si può più cambiare.",
        "usage_cn": "事情已经发生了，后悔也没用，应该向前看。",
        "examples": [
            ("A", "Non riesco a credere di aver perso quel treno, ora arriverò in ritardo di due ore...", "我不敢相信我错过了那趟火车，现在要晚到两小时……"),
            ("B", "Ormai è fatta, non piangere sul latte versato. Chiama un taxi e recupera il tempo perso.", "事已至此，别为打翻的牛奶哭泣了。叫辆出租车，把时间补回来。"),
        ],
        "cultural_cn": "「piangere = 哭泣」「sul latte = 在牛奶上」「versato = 打翻的」。打翻的牛奶无法收回。相当于英语的「Crying over spilt milk」。",
        "exercise_q": [
            {'question': '「Piangere sul latte versato」的意思是？', 'options': ['È importante piangere quando si è tristi', 'Bisogna lamentarsi per ogni piccolo errore commesso', 'È inutile disperarsi per qualcosa che non si può più cambiare', 'Il latte versato è pericoloso per la salute'], 'answer': 'C) È inutile disperarsi per qualcosa che non si può più cambiare'},
            {'question': 'Hai sbagliato a inviare quella email, ma ormai _____________________________________________ . Invia una rettifica e vai avanti.', 'fill': ['piangere sul latte versato']},
        ],
        "english_eq": "Crying over spilt milk",
        "meaning_it_cn": "为无法改变的事情而绝望是徒劳的。",
    },
    {
        "id": 22,
        "idiom": "Chi fa da sé fa per tre.",
        "category": "Indipendenza / Azione",
        "meaning_cn": "自己动手，胜过三人。/ 求人不如求己。",
        "meaning_it": "Una persona che lavora da sola è spesso più efficiente di un gruppo.",
        "usage_cn": "与其等待别人帮忙，不如自己动手做。",
        "examples": [
            ("A", "Ho aspettato tre giorni che il collega mi mandasse i dati, ma niente...", "我等了三天同事给我发数据，但什么也没有……"),
            ("B", "Alla fine hai fatto tutto da sola, vero? Chi fa da sé fa per tre!", "最后你全都自己做了，对吧？求人不如求己！"),
        ],
        "cultural_cn": "「chi fa da sé = 自己做的人」「fa per tre = 做三个人的量」。这句话体现了意大利人务实、自力更生的精神。",
        "exercise_q": [
            {'question': '「Chi fa da sé fa per tre」的意思是？', 'options': ['Lavorare in gruppo è sempre la scelta migliore', 'Una persona che lavora da sola è spesso più efficiente di un gruppo', 'Tre persone sono necessarie per ogni lavoro', 'Chi è pigro lavora come tre persone'], 'answer': 'B) Una persona che lavora da sola è spesso più efficiente di un gruppo'},
            {'question': 'Non aspettare che tuo fratello ti aiuti a montare il mobile. Prendi il cacciavite e ________________________________ . Finisci prima e impari come fare.', 'fill': ['chi fa da sé fa per tre']},
        ],
        "english_eq": "If you want something done right, do it yourself",
        "meaning_it_cn": "独自工作的人往往比一个团队更有效率。",
    },
    {
        "id": 23,
        "idiom": "Ogni scarafone è bello a mamma sua.",
        "category": "Famiglia / Gusto personale",
        "meaning_cn": "孩子都是自己的好。/ 情人眼里出西施。",
        "meaning_it": "Ognuno ha i propri gusti e ciò che è bello per uno può non esserlo per un altro.",
        "usage_cn": "当有人批评别人的喜好时，用来捍卫多元审美。",
        "examples": [
            ("A", "Non capisco perché ti piaccia così tanto quel vecchio film, è lento e noioso...", "我不明白你为什么那么喜欢那部老电影，又慢又无聊……"),
            ("B", "Beh, ogni scarafone è bello a mamma sua! Io lo trovo un classico intramontabile.", "呃，情人眼里出西施！我觉得它是永不过时的经典。"),
        ],
        "cultural_cn": "「scarafone = 蟑螂」「bello a mamma sua = 在它妈妈眼里是美的」。幽默地说即使蟑螂在妈妈眼中也是美的。相当于英语的「Beauty is in the eye of the beholder」。",
        "exercise_q": [
            {'question': '「Ogni scarafone è bello a mamma sua」的意思是？', 'options': ['Le madri amano solo gli insetti belli', 'Ognuno ha i propri gusti e ciò che è bello per uno può non esserlo per un altro', 'Gli scarafaggi sono animali molto eleganti', 'Bisogna sempre criticare i gusti degli altri'], 'answer': 'B) Ognuno ha i propri gusti e ciò che è bello per uno può non esserlo per un altro'},
            {'question': 'Non capisco perché tu preferisca la pizza di Napoli a quella di Roma, ma ____________________________________ . A ciascuno il suo!', 'fill': ['ogni scarafone è bello a mamma sua']},
        ],
        "english_eq": "Beauty is in the eye of the beholder",
        "meaning_it_cn": "每个人都有自己的品味，对一个人来说是美的东西对另一个人来说可能不是。",
    },
    {
        "id": 24,
        "idiom": "Battere il ferro finché è caldo.",
        "category": "Opportunità / Azione",
        "meaning_cn": "趁热打铁。",
        "meaning_it": "Bisogna approfittare di un'occasione favorevole prima che passi.",
        "usage_cn": "机会来了要立刻抓住，不要拖延。",
        "examples": [
            ("A", "Ho appena superato il colloquio e il responsabile mi ha chiesto di inviare i documenti entro domani...", "我刚通过了面试，负责人让我明天之前把文件发过去……"),
            ("B", "Ottimo! Battere il ferro finché è caldo: prepara tutto stasera e spedisci subito.", "太好了！趁热打铁：今晚就准备好，马上发出去。"),
        ],
        "cultural_cn": "「battere = 敲打」「il ferro = 铁」「finché è caldo = 趁着还热」。铁匠趁铁烧红时锻造。相当于英语的「Strike while the iron is hot」。",
        "exercise_q": [
            {'question': '「Battere il ferro finché è caldo」的意思是？', 'options': ['Bisogna lavorare sodo come un fabbro', "Bisogna approfittare di un'occasione favorevole prima che passi", 'Il metallo deve essere sempre caldo per essere usato', 'Non bisogna mai fermarsi quando si è stanchi'], 'answer': "B) Bisogna approfittare di un'occasione favorevole prima che passi"},
            {'question': 'Hai appena ricevuto una buona offerta di lavoro, non aspettare: _____________________________ . Accetta subito o rischi di perderla.', 'fill': ['battere il ferro finché è caldo']},
        ],
        "english_eq": "Strike while the iron is hot",
        "meaning_it_cn": "在有利时机过去之前要充分利用它。",
    },
    {
        "id": 25,
        "idiom": "L'unione fa la forza.",
        "category": "Collaborazione / Comunità",
        "meaning_cn": "团结就是力量。",
        "meaning_it": "Collaborare insieme rende possibile superare ostacoli difficili.",
        "usage_cn": "鼓励团队合作，强调集体的力量大于个人。",
        "examples": [
            ("A", "Non ce la facciamo da soli a organizzare la festa di quartiere, siamo troppo pochi...", "我们几个人搞不定社区聚会，人太少了……"),
            ("B", "Non preoccuparti, chiediamo aiuto ai vicini. L'unione fa la forza!", "别担心，找邻居帮忙。团结就是力量！"),
        ],
        "cultural_cn": "「l'unione = 联合/团结」「fa = 造就」「la forza = 力量」。这是意大利统一运动中的重要口号，现在已是普世智慧。",
        "exercise_q": [
            {'question': "「L'unione fa la forza」的意思是？", 'options': ['Solo i muscoli rendono forti', 'Collaborare insieme rende possibile superare ostacoli difficili', 'Bisogna sempre fare tutto da soli', "La forza fisica è l'unica cosa che conta"], 'answer': 'B) Collaborare insieme rende possibile superare ostacoli difficili'},
            {'question': 'Non litigate per piccole cose, ragazzi. Ricordatevi che _______________________________________ : solo insieme possiamo vincere questa competizione.', 'fill': ["l'unione fa la forza"]},
        ],
        "english_eq": "Unity is strength",
        "meaning_it_cn": "合作一起可以克服艰难的障碍。",
    },
    {
        "id": 26,
        "idiom": "Volere la botte piena e la moglie ubriaca.",
        "category": "Ironia / Realismo",
        "meaning_cn": "既要马儿跑，又要马儿不吃草。/ 鱼和熊掌不可兼得。",
        "meaning_it": "Desiderare due cose contraddittorie o impossibili da ottenere insieme.",
        "usage_cn": "批评那些想要两件互相矛盾的事情的人。",
        "examples": [
            ("A", "Vorrei comprare una villa al mare spendendo solo 100.000 euro...", "我想花十万欧元买一栋海景别墅……"),
            ("B", "Ma dai, tu vuoi avere la botte piena e la moglie ubriaca! Non esistono case così a quel prezzo.", "得了吧，你这是鱼和熊掌都想兼得！这个价哪买得到这样的房子。"),
        ],
        "cultural_cn": "「botte piena = 装满的酒桶」「moglie ubriaca = 喝醉的妻子」。想要酒桶是满的（酒没被喝掉）又想要妻子喝醉，这两件事不可能同时成立。一个极具意大利特色的幽默谚语。",
        "exercise_q": [
            {'question': '「Volere la botte piena e la moglie ubriaca」的意思是？', 'options': ['È importante festeggiare con il vino e la famiglia', 'Si desiderano due cose contraddittorie o impossibili da ottenere insieme', 'Bisogna sempre sposare una persona allegra', "Il vino e la felicità non vanno d'accordo"], 'answer': 'B) Si desiderano due cose contraddittorie o impossibili da ottenere insieme'},
            {'question': 'Vuoi un lavoro pagato bene, vicino a casa e senza stress? Smettila di _______________________________________ : devi scegliere cosa è più importante per te.', 'fill': ['volere la botte piena e la moglie ubriaca']},
        ],
        "english_eq": "Have your cake and eat it too",
        "meaning_it_cn": "想要两个相互矛盾或不可能同时获得的东西。",
    },
    {
        "id": 27,
        "idiom": "Stare con i piedi per terra.",
        "category": "Realismo / Saggezza",
        "meaning_cn": "脚踏实地 / 实事求是。",
        "meaning_it": "Avere un atteggiamento realistico e pratico, senza illusioni.",
        "usage_cn": "劝人务实，不要好高骛远。",
        "examples": [
            ("A", "Ho deciso di diventare milionario entro l'anno prossimo senza investire un euro...", "我决定不投资一分钱，明年就成为百万富翁……"),
            ("B", "Sii realista, devi stare con i piedi per terra. Inizia con obiettivi più modesti e raggiungibili.", "现实一点，你得脚踏实地。先从更务实、可实现的目标开始。"),
        ],
        "cultural_cn": "「stare = 站立」「con i piedi = 用脚」「per terra = 在地上」。双脚踩在地上，形容人务实、不飘。相当于英语的「Keep your feet on the ground」。",
        "exercise_q": [
            {'question': '「Stare con i piedi per terra」的意思是？', 'options': ["Camminare scalzi all'aperto", 'Avere un atteggiamento realistico e pratico, senza illusioni', 'Lavorare solo nei campi', 'Non volare mai in aereo'], 'answer': 'B) Avere un atteggiamento realistico e pratico, senza illusioni'},
            {'question': 'Se vuoi davvero aprire una tua attività, devi ______________________________ : studia il mercato e prepara un piano concreto.', 'fill': ['stare con i piedi per terra']},
        ],
        "english_eq": "Keep your feet on the ground / Be down-to-earth",
        "meaning_it_cn": "拥有现实和务实的态度，不抱幻想。",
    },
    {
        "id": 28,
        "idiom": "Chi la dura la vince.",
        "category": "Perseveranza / Determinazione",
        "meaning_cn": "坚持就是胜利。",
        "meaning_it": "Chi continua a insistere nonostante le difficoltà otterrà successo.",
        "usage_cn": "鼓励人不要放弃，坚持到底就会成功。",
        "examples": [
            ("A", "Studio l'italiano da un anno ma a volte mi sento ancora insicuro quando parlo...", "我学意大利语一年了，但说话时还是没信心……"),
            ("B", "Non mollare! Chi la dura la vince. Continua a esercitarti e vedrai grandi miglioramenti.", "别放弃！坚持就是胜利。继续练习，你会看到巨大进步的。"),
        ],
        "cultural_cn": "「chi la dura = 坚持的人（durare = 持续）」「la vince = 赢（vincere）」。这里的「la」是语法上的宾语，指代「这场斗争」。",
        "exercise_q": [
            {'question': '「Chi la dura la vince」的意思是？', 'options': ['Chi è forte fisicamente vince sempre', 'Chi continua a insistere nonostante le difficoltà otterrà successo', 'La vittoria arriva solo ai giovani', 'Bisogna durare poco per vincere'], 'answer': 'B) Chi continua a insistere nonostante le difficoltà otterrà successo'},
            {'question': 'Non smettere di provare a suonare quel pezzo al pianoforte, anche se è difficile. ______________________________ : alla fine ci riuscirai perfettamente.', 'fill': ['Chi la dura la vince']},
        ],
        "english_eq": "Persistence pays off / He who perseveres wins",
        "meaning_it_cn": "尽管困难仍坚持的人终将获得成功。",
    },
    {
        "id": 29,
        "idiom": "Cercare il pelo nell'uovo.",
        "category": "Critica / Perfezionismo",
        "meaning_cn": "鸡蛋里挑骨头。/ 吹毛求疵。",
        "meaning_it": "Cercare difetti inesistenti o essere eccessivamente pignoli.",
        "usage_cn": "批评那些对微小的、无关紧要的细节过分挑剔的人。",
        "examples": [
            ("A", "Questo ristorante è carino, ma il tovagliolo non è stirato perfettamente e la musica è un po' alta...", "这家餐厅不错，但餐巾熨得不够平整，音乐也有点吵……"),
            ("B", "Dai, smettila di cercare il pelo nell'uovo! Goditi il cibo e la compagnia.", "得了，别鸡蛋里挑骨头了！享受美食和同伴吧。"),
        ],
        "cultural_cn": "「cercare = 寻找」「il pelo = 毛发」「nell'uovo = 在鸡蛋里」。鸡蛋里面怎么可能有毛？所以是在找不可能存在的缺陷。",
        "exercise_q": [
            {'question': "「Cercare il pelo nell'uovo」的意思是？", 'options': ['È importante pulire accuratamente le uova prima di cucinare', 'Cercare difetti inesistenti o essere eccessivamente pignoli su dettagli minimi', 'Gli uomini sono come le uova, bisogna esaminarli bene', 'Bisogna sempre trovare qualcosa di positivo in ogni situazione'], 'answer': 'B) Cercare difetti inesistenti o essere eccessivamente pignoli su dettagli minimi'},
            {'question': 'Il tuo nuovo appartamento è bellissimo, non __________________________________________________________ sul colore delle pareti che comunque possiamo ridipingere.', 'fill': ["cercare il pelo nell'uovo"]},
        ],
        "english_eq": "Split hairs / Nitpick",
        "meaning_it_cn": "寻找不存在的缺陷，或在微小细节上过分挑剔。",
    },
    {
        "id": 30,
        "idiom": "Chi va con lo zoppo impara a zoppicare.",
        "category": "Influenza / Relazioni",
        "meaning_cn": "近朱者赤，近墨者黑。",
        "meaning_it": "Frequentare certe persone ci porta ad assomigliare a loro.",
        "usage_cn": "提醒人注意选择交往的对象，因为你会不自觉地被他们影响。",
        "examples": [
            ("A", "Non capisco perché mio figlio sia diventato così pigro ultimamente...", "我不明白为什么我儿子最近变得这么懒……"),
            ("B", "Guarda con chi passa il tempo! Chi va con lo zoppo impara a zoppicare. Dovrebbe frequentare ragazzi più ambiziosi.", "看看他和谁在一起！近朱者赤，近墨者黑。他应该和有抱负的孩子多交往。"),
        ],
        "cultural_cn": "「zoppo = 瘸子」「zoppicare = 瘸着走」。和瘸子一起走路，会不自觉地学他跛行的样子。",
        "exercise_q": [
            {'question': '「Chi va con lo zoppo impara a zoppicare」的意思是？', 'options': ['Bisogna aiutare le persone con disabilità', 'Frequentare certe persone ci porta ad assomigliare a loro, nel bene e nel male', 'Camminare molto fa venire i calli', 'Chi è zoppo non deve uscire di casa'], 'answer': 'B) Frequentare certe persone ci porta ad assomigliare a loro, nel bene e nel male'},
            {'question': 'Non uscire con quella banda di ragazzi che marinano la scuola. Ricorda: _______________________________________ . Non rovinare il tuo futuro.', 'fill': ['chi va con lo zoppo impara a zoppicare']},
        ],
        "english_eq": "He who walks with the lame learns to limp",
        "meaning_it_cn": "和某些人交往会使我们变得像他们，无论好坏。",
    },
    {
        "id": 31,
        "idiom": "Dimmi con chi vai e ti dirò chi sei.",
        "category": "Relazioni / Giudizio",
        "meaning_cn": "观其友，知其人。/ 告诉我你和谁在一起，我就知道你是谁。",
        "meaning_it": "La compagnia che frequentiamo riflette il nostro carattere.",
        "usage_cn": "通过一个人交往的朋友来判断他的品性。",
        "examples": [
            ("A", "Non capisco perché i miei genitori non vogliano che esca con quella compagnia...", "我不明白为什么我父母不让我和那帮人出去……"),
            ("B", "Sai com'è il detto: dimmi con chi vai e ti dirò chi sei. Loro temono che tu diventi come loro.", "你知道那句老话：观其友，知其人。他们担心你变得和他们一样。"),
        ],
        "cultural_cn": "「dimmi = 告诉我（dire的命令式）」「con chi vai = 你和谁一起去」「ti dirò chi sei = 我会告诉你你是谁」。这是意大利版的「物以类聚，人以群分」。",
        "exercise_q": [
            {'question': '「Dimmi con chi vai e ti dirò chi sei」的意思是？', 'options': ['Bisogna sempre dire agli altri dove si va', 'La compagnia che frequentiamo riflette il nostro carattere e i nostri valori', 'Chi viaggia molto conosce molte persone', 'Bisogna cambiare amici ogni anno'], 'answer': 'B) La compagnia che frequentiamo riflette il nostro carattere e i nostri valori'},
            {'question': 'Non fidarti di lui, ha amici poco raccomandabili. Ricorda il proverbio: ______________________________________________________________________ .', 'fill': ['Dimmi con chi vai e ti dirò chi sei']},
        ],
        "english_eq": "Tell me who you walk with and I'll tell you who you are",
        "meaning_it_cn": "我们交往的伙伴反映了我们的性格和价值观。",
    },
    {
        "id": 32,
        "idiom": "Acqua in bocca!",
        "category": "Segretezza / Riservatezza",
        "meaning_cn": "守口如瓶！/ 保密！",
        "meaning_it": "Invito a mantenere un segreto, a non rivelare ciò che si è appreso.",
        "usage_cn": "告诉别人一个秘密后，提醒对方不要告诉其他人。相当于中文的「嘴严一点！」。",
        "examples": [
            ("A", "Ti racconto una cosa, ma acqua in bocca!", "我告诉你一件事，但要守口如瓶哦！"),
            ("B", "Tranquillo, non dirò niente a nessuno.", "放心吧，我谁都不说。"),
            ("A", "Hai sentito che Maria e Luca si sono lasciati?", "你听说了吗，Maria和Luca分手了？"),
            ("B", "Sì, ma acqua in bocca, non voglio che si sappia in giro.", "听说了，但你别说出去，我不想让大家都知道。"),
        ],
        "cultural_cn": "「Acqua = 水」「in bocca = 在嘴里」。字面意思是「把水含在嘴里」——嘴里含了水就说不了话了，所以意为「闭嘴保密」。这是一个非常常用的日常表达，类似于英语的「Mum's the word!」。",
        "exercise_q": [
            {'question': '「Acqua in bocca!」的意思是？', 'options': ['Hai sete?', 'Tieni un segreto, non rivelarlo!', 'Bevi un po\' d\'acqua!', 'Parla più forte!'], 'answer': 'B) Tieni un segreto, non rivelarlo!'},
            {'question': 'Completa: Ti racconto una cosa, ma _________ _________ !', 'fill': ['Acqua in bocca']},
        ],
        "english_eq": "Mum's the word! / Keep it under wraps!",
        "meaning_it_cn": "邀请对方保守秘密，不要泄露所知道的事情。",
    },
    {
        "id": 33,
        "idiom": "Essere al verde",
        "category": "Economia / Difetto",
        "meaning_cn": "身无分文 / 一贫如洗",
        "meaning_it": "Non avere più denaro, essere senza soldi.",
        "usage_cn": "描述一个人完全没钱了。可以用于任何时态。「Sono al verde」=「我身无分文」。",
        "examples": [
            ("A", "Possiamo andare a cena fuori stasera?", "我们今晚能出去吃饭吗？"),
            ("B", "Mi dispiace, ma sono al verde. Dobbiamo aspettare la fine del mese.", "抱歉，我现在身无分文。得等到月底。"),
            ("A", "Hai comprato il nuovo iPhone?", "你买新iPhone了吗？"),
            ("B", "Macché, dopo le vacanze sono completamente al verde!", "哪能啊，度假之后我就彻底一贫如洗了！"),
        ],
        "cultural_cn": "「Essere=是」「al verde=在绿色上」。这个词源自中世纪佛罗伦萨的习俗——在蜡烛底部标绿色刻度线，当蜡烛烧到绿线处说明时间到了。后来引申到钱的概念：当某人的银行账户余额用烛火烧光了、到了「绿色标记」处，就意味着没钱了。另一说法源自拍卖：出价时手持绿色蜡烛，烛光熄灭则出价停止。现代意大利语中非常常用，和英语的「to be in the red」相反（意大利人用绿色代表透支）。",
        "exercise_q": [
            {'question': '「Essere al verde」的正确含义是？', 'options': ['Avere molti soldi', 'Non avere più denaro', 'Essere invidioso', 'Vivere in campagna'], 'answer': 'B) Non avere più denaro'},
            {'question': 'Completa: Dopo aver pagato l\'affitto, sono completamente ___ ___.', 'fill': ['al verde']},
        ],
        "english_eq": "To be broke / To be flat broke",
        "meaning_it_cn": "没有更多钱了，身无分文。",
    },
    {
        "id": 34,
        "idiom": "Non avere peli sulla lingua",
        "category": "Critica / Influenza / Saggezza",
        "meaning_cn": "直言不讳 / 心直口快 / 有话直说",
        "meaning_it": "Parlare in modo diretto e sincero, senza timore di offendere.",
        "usage_cn": "形容一个人说话直来直去，不会为了讨好人而拐弯抹角。通常带有赞赏意味。",
        "examples": [
            ("A", "Cosa pensi veramente del mio nuovo taglio di capelli?", "你实话告诉我，你觉得我的新发型怎么样？"),
            ("B", "Sinceramente? Non mi piace molto. Lo sai che io non ho peli sulla lingua.", "说实话？我不太喜欢。你知道我向来直言不讳。"),
            ("A", "Marco ha detto al capo quello che pensava di lui...", "Marco直接跟老板说了他对他的看法……"),
            ("B", "Beh, Marco non ha peli sulla lingua. Almeno si è tolto un peso.", "嗯，Marco就是心直口快。至少他说出来心里舒服了。"),
        ],
        "cultural_cn": "「peli = 毛发」「sulla lingua = 在舌头上」。字面意思是「舌头上没有毛」。如果舌头上有毛，说话就会含糊不清——没有毛就意味着说话利索、直接。这个表达在意大利非常常用，和英语的「to not mince words」类似。注意「pelo」是单数，「peli」是复数，但习惯用复数形式。",
        "exercise_q": [
            {'question': '「Non avere peli sulla lingua」的意思是？', 'options': ['Avere un problema di pronuncia', 'Parlare in modo diretto e sincero', 'Essere timido e silenzioso', 'Non riuscire a parlare'], 'answer': 'B) Parlare in modo diretto e sincero'},
            {'question': 'Completa: Lo sai che Marta è sincera, lei non ha ___ sulla ___.', 'fill': ['peli sulla lingua']},
        ],
        "english_eq": "To not mince words / To speak one's mind",
        "meaning_it_cn": "直接而真诚地说话，不害怕冒犯别人。",
    },
    {
        "id": 35,
        "idiom": "Essere come il prezzemolo",
        "category": "Critica / Difetto / Ironia",
        "meaning_cn": "无处不在 / 哪里都有他 / 多余碍事",
        "meaning_it": "Essere presente ovunque, spesso in modo invadente o inopportuno.",
        "usage_cn": "贬义用法，形容一个人总是出现在各种场合，尤其是他不该出现的地方。也用于形容某种事物随处可见。",
        "examples": [
            ("A", "Ho incontrato Marco anche alla festa di Luisa... è dappertutto!", "我在Luisa的派对上又遇到了Marco……他真是无处不在！"),
            ("B", "Eh già, Marco è come il prezzemolo: lo trovi in tutte le feste!", "是啊，Marco就像香菜一样：哪里都有他！"),
            ("A", "Secondo te chi dovrebbe organizzare la gita?", "你觉得谁应该组织这次郊游？"),
            ("B", "Di nuovo Mario? Ma è come il prezzemolo, si intromette sempre in tutto!", "又是Mario？他怎么跟香菜似的，什么事都要插手！"),
        ],
        "cultural_cn": "「Prezzemolo = 欧芹/香菜」。欧芹是意大利菜肴中最常见的配菜装饰（garnish），几乎每一道菜上桌时都会撒一点。所以「像欧芹一样」就用来比喻一个人无处不在。类似的表达还有「esserci come il prezzemolo」（像欧芹一样存在）。注意这是个略带贬义的表达。",
        "exercise_q": [
            {'question': '「Essere come il prezzemolo」形容什么样的人？', 'options': ['Una persona che ama cucinare', 'Una persona presente ovunque, spesso invadente', 'Una persona molto elegante', 'Una persona che mangia molta verdura'], 'answer': 'B) Una persona presente ovunque, spesso invadente'},
            {'question': 'Completa: Mario si intromette in tutto, è come ___ ___.', 'fill': ['il prezzemolo']},
        ],
        "english_eq": "To be everywhere / To pop up like a bad penny",
        "meaning_it_cn": "到处出现，常指以令人讨厌或不恰当的方式。",
    },
    {
        "id": 36,
        "idiom": "Avere un diavolo per capello",
        "category": "Emozioni / Rabbia",
        "meaning_cn": "暴跳如雷 / 火冒三丈 / 非常生气",
        "meaning_it": "Essere molto arrabbiato, irritato o nervoso per qualcosa.",
        "usage_cn": "描述一个人因为某事而极度愤怒，好像每根头发都被一个小魔鬼占据着。用于表达极度生气的状态。",
        "examples": [
            ("A", "Cosa è successo al capo? Oggi ha un diavolo per capello!", "老板怎么了？今天他暴跳如雷！"),
            ("B", "Ha scoperto che il progetto non è stato completato in tempo.", "他发现项目没有按时完成。"),
            ("A", "Perché Maria ha un diavolo per capello stamattina?", "为什么Maria今早火冒三丈？"),
            ("B", "Le hanno rubato la bici nuova. È furiosa!", "她的新自行车被偷了。她气疯了！"),
        ],
        "cultural_cn": "「Avere = 有」「un diavolo = 一个魔鬼」「per capello = 每根头发」。字面意思是「每根头发上都有一个魔鬼」。这个表达源自意大利民间想象：当你极度愤怒时，头发都竖起来了，好像每根头发上都有一个小恶魔在作祟。相当于英语的「to be hopping mad」或「to be furious」。",
        "exercise_q": [
            {'question': '「Avere un diavolo per capello」的意思是？', 'options': ['Avere un problema medico ai capelli', 'Essere molto arrabbiato o irritato', 'Indossare un cappello decorato con diavoli', 'Avere un diavoletto come animale domestico'], 'answer': 'B) Essere molto arrabbiato o irritato'},
            {'question': 'Completa: Stamattina il professore ________ un _______ per _______, meglio stare zitti.', 'fill': ['ha, diavolo, capello']},
        ],
        "english_eq": "To be hopping mad / To be furious",
        "meaning_it_cn": "因为某事而感到非常生气、恼怒或紧张。",
    },
    {
        "id": 37,
        "idiom": "Sputa il rospo!",
        "category": "Comunicazione / Sincerità",
        "meaning_cn": "有话直说！/ 快说吧！/ 别吞吞吐吐的！",
        "meaning_it": "Espressione usata per invitare qualcuno a dire finalmente ciò che ha da dire, specialmente una verità nascosta o una confessione.",
        "usage_cn": "当某人欲言又止、犹豫不决时说这句话，催促对方把憋在心里的话说出来。语气比较直接甚至粗鲁。",
        "examples": [
            ("A", "Beh... cioè... non so se dirtelo...", "嗯……就是说……我不知道该不该告诉你……"),
            ("B", "Allora? Sputa il rospo! Cosa è successo?", "那又怎样？快说吧！发生什么事了？"),
            ("A1", "Ieri ho visto Marco con un'altra ragazza.", "我昨天看见Marco和另一个女孩在一起。"),
            ("B1", "Ah, finalmente hai sputato il rospo! Lo sospettavo da tempo.", "啊，你终于肯说出来了！我早就怀疑了。"),
        ],
        "cultural_cn": "「Sputare = 吐出来」「rospo = 蟾蜍/癞蛤蟆」。字面意思是「把癞蛤蟆吐出来！」。传说中如果有人把蛤蟆吞下去了，肚子会非常难受，只有吐出来才能解脱。这个表达形象地比喻憋着秘密不说会像吞了蛤蟆一样难受，不如痛痛快快说出来。相当于英语的「Spit it out!」或「Spill the beans!」。",
        "exercise_q": [
            {'question': '「Sputa il rospo!」用于什么场景？', 'options': ['Quando qualcuno mangia troppo velocemente', 'Quando qualcuno esita a dire qualcosa', 'Quando qualcuno ha un animale in bocca', 'Quando qualcuno sta male fisicamente'], 'answer': 'B) Quando qualcuno esita a dire qualcosa'},
            {'question': 'Completa: Non fare il misterioso, ________ il ________ e dimmi tutto!', 'fill': ['sputa, rospo']},
        ],
        "english_eq": "Spit it out! / Spill the beans!",
        "meaning_it_cn": "用来邀请某人最终说出他想说的话，尤其是一个隐藏的真相或坦白。",
    },
    {
        "id": 38,
        "idiom": "Morto un papa, se ne fa un altro",
        "category": "Realismo / Saggezza",
        "meaning_cn": "没有谁是不可替代的 / 地球离了谁都转",
        "meaning_it": "Espressione che significa che nessuno è insostituibile; dopo una perdita, la vita continua e qualcun altro prenderà il posto.",
        "usage_cn": "用于安慰失去某人或某事的情况，或表达某种职位/角色总有替代者。语气比较实在，有时带点冷幽默。",
        "examples": [
            ("A", "Sono triste che il nostro capo se ne vada. Era una persona fantastica.", "老板要走了我好难过。他是个很棒的人。"),
            ("B", "Morto un papa, se ne fa un altro. Arriverà qualcuno di altrettanto bravo.", "没有谁是不可替代的。会来一个同样出色的人。"),
            ("A1", "Mario ha lasciato la squadra, adesso come faremo?", "Mario离开了团队，我们怎么办？"),
            ("B1", "Morto un papa, se ne fa un altro. Troveremo un sostituto.", "地球离了谁都转。我们会找到替代者的。"),
        ],
        "cultural_cn": "「Morto = 死了」「un papa = 一个教皇」「se ne fa un altro = 再立一个」。字面意思是「一个教皇死了，再立一个」。这句话源自天主教教皇选举制度——教皇去世后，枢机团立即会选举新的继任者。这个表达现已广为流传，用来表明「没有谁是不可替代的」，任何人的离开都不会让世界停止运转。相当于英语的「The king is dead, long live the king!」。",
        "exercise_q": [
            {'question': '「Morto un papa, se ne fa un altro」表达什么意思？', 'options': ['I papi sono immortali', 'Nessuno è insostituibile', 'Bisogna sempre piangere i morti', 'I papi sono tutti uguali'], 'answer': 'B) Nessuno è insostituibile'},
            {'question': 'Completa: ________ un papa, se ne fa un ________.', 'fill': ['Morto, altro']},
        ],
        "english_eq": "The king is dead, long live the king! / No one is irreplaceable",
        "meaning_it_cn": "表达没有人是不可替代的；失去之后，生活继续，会有其他人接替。",
    },
    {
        "id": 39,
        'idiom': 'Avere la testa tra le nuvole',
        'category': 'Attenzione / Distrazione',
        'meaning_cn': '心不在焉 / 走神 / 胡思乱想',
        'meaning_it': 'Essere distratto, assente, perso nei propri pensieri, non concentrato su ciò che si sta facendo.',
        'usage_cn': '形容一个人注意力不集中，脑子里在想别的事情，像头埋在云里一样。通常带点善意的批评或调侃。',
        'examples': [
            ('A', 'Marco, cosa ha detto il professore?', 'Marco，老师刚才说了什么？'),
            ('B', 'Scusa, non ho sentito. Avevo la testa tra le nuvole.', '抱歉我没听到，我走神了。'),
            ('A1', 'Ieri ho lasciato le chiavi in macchina perché avevo la testa tra le nuvole.', '昨天我把钥匙落在车里了，因为我心不在焉。'),
            ('B1', 'Ultimamente sei sempre distratto! Hai la testa tra le nuvole.', '你最近总是心不在焉！魂不守舍的。')
        ],
        'cultural_cn': '「Avere = 有」「la testa = 头」「tra le nuvole = 在云里」。字面意思是「头在云里」。这个表达在意大利语中非常常见，描述一个人沉浸在自己的思绪里，对外界浑然不觉。就像云朵一样飘忽不定。英语有完全相同的表达「To have one\'s head in the clouds」。',
        'exercise_q': [
            {'question': '「Avere la testa tra le nuvole」指什么样的人？', 'options': ['Una persona molto felice', 'Una persona distratta che non ascolta', 'Una persona che ama volare', 'Una persona che guarda spesso il cielo'], 'answer': 'B) Una persona distratta che non ascolta'},
            {'question': 'Completa: Oggi Marco non ascolta niente, ha la ________ tra le ________.', 'fill': ['testa, nuvole']},
        ],
        'english_eq': 'To have one\'s head in the clouds / To be daydreaming',
        'meaning_it_cn': '心不在焉、走神、沉浸在自己的思绪中，不专注于正在做的事情。',
    },

    {
        "id": 40,
        'idiom': 'Alzare il gomito',
        'category': 'Piacere / Vizio',
        'meaning_cn': '喝酒（尤其是过量饮酒）/ 酗酒',
        'meaning_it': 'Bere alcolici, spesso in grande quantità o in modo eccessivo.',
        'usage_cn': '主要用于指喝酒喝得多，有时也泛指饮酒。语气偏口语化，可带调侃或批评意味。',
        'examples': [
            ('A', 'Ieri sera Marco ha alzato un po\' troppo il gomito alla festa.', '昨晚Marco在派对上喝得有点多。'),
            ('B', 'Infatti oggi ha un gran mal di testa!', '难怪他今天头疼得厉害！'),
            ('A1', 'Da quando ha perso il lavoro, alza il gomito sempre più spesso.', '自从丢了工作，他就越来越频繁地酗酒。'),
            ('B1', 'Dovrebbe chiedere aiuto, così non va bene.', '他应该寻求帮助，这样下去不行。')
        ],
        'cultural_cn': '「Alzare = 抬起」「il gomito = 手肘」。字面意思是「抬起手肘」，因为喝酒时手臂抬起使手肘上翘的动作。这个表达据说起源于人们围坐饮酒时，举杯自然抬肘的动作。英语中有类似的「raise one\'s elbow」或「bend one\'s elbow」。',
        'exercise_q': [
            {'question': '「Alzare il gomito」是什么意思？', 'options': ['Fare ginnastica', 'Bere alcolici / ubriacarsi', 'Salutare qualcuno', 'Alzare un oggetto pesante'], 'answer': 'B) Bere alcolici / ubriacarsi'},
            {'question': 'Completa: Dopo la festa, tutti hanno alzato un po\' troppo __ ______.', 'fill': ['il gomito']},
        ],
        'english_eq': 'To hit the bottle / To booze / To bend one\'s elbow',
        'meaning_it_cn': '喝酒，常指大量或过量饮酒。',
    },

    {
        "id": 41,
        'idiom': 'Avere l\'argento vivo addosso',
        'category': 'Energia / Attività',
        'meaning_cn': '坐不住 / 好动 / 像身上有跳蚤一样',
        'meaning_it': 'Essere molto irrequieto, non riuscire a stare fermo, essere pieno di energia incontenibile.',
        'usage_cn': '形容人（尤其小孩）特别好动、坐不住、浑身是劲。常带善意的调侃。',
        'examples': [
            ('A', 'Quel bambino non sta fermo un minuto! Ha l\'argento vivo addosso!', '那孩子一分钟都坐不住！身上像有跳蚤一样！'),
            ('B', 'Eh sì, è proprio un vulcano di energia!', '是啊，他就是个小火山！'),
            ('A1', 'Oggi non riesco a concentrarmi, ho l\'argento vivo addosso.', '今天我没办法集中注意力，浑身坐不住。'),
            ('B1', 'Forse hai bevuto troppo caffè!', '可能是咖啡喝太多了！')
        ],
        'cultural_cn': '「Avere = 有」「l\'argento vivo = 活银（水银）」「addosso = 在身上」。字面意思是「身上有活银」。在中世纪，水银（argento vivo）因其不断流动的特性被视为「活的银」，人们认为如果身上沾了水银，就会不停地动。这个表达如今用来形容精力旺盛、一刻也停不下来的人。相当于英语的「to have ants in one\'s pants」。',
        'exercise_q': [
            {'question': '「Avere l\'argento vivo addosso」形容什么样的人？', 'options': ['Una persona molto ricca', 'Una persona irrequieta che non sta ferma', 'Una persona che lavora con l\'argento', 'Una persona molto fredda'], 'answer': 'B) Una persona irrequieta che non sta ferma'},
            {'question': 'Completa: Quel bambino non sta mai fermo, ha l\'argento ________ addosso.', 'fill': ['vivo']},
        ],
        'english_eq': 'To have ants in one\'s pants / To be fidgety',
        'meaning_it_cn': '非常不安分，无法保持安静，充满无法抑制的能量。',
    },

    {
        "id": 42,
        'idiom': 'Andare a gonfie vele',
        'category': 'Successo / Progresso',
        'meaning_cn': '一帆风顺 / 进展顺利 / 蓬勃发展',
        'meaning_it': 'Procedere molto bene, avere successo, andare avanti senza problemi.',
        'usage_cn': '形容事情进行得非常顺利，像顺风航行的帆船一样。常用于描述工作、项目、关系等进展顺利。',
        'examples': [
            ('A', 'Come va il nuovo progetto?', '新项目进展如何？'),
            ('B', 'Va a gonfie vele! Abbiamo già superato tutti i test.', '一帆风顺！我们已经通过了所有测试。'),
            ('A1', 'Il suo business va a gonfie vele quest\'anno.', '他今年生意做得风生水起。'),
            ('B1', 'Sì, ha aperto tre nuovi negozi!', '是啊，他开了三家新店！')
        ],
        'cultural_cn': '「Andare = 走/航行」「a gonfie vele = 帆满的/帆鼓起来的」。字面意思是「帆满地航行」。在航海中，如果帆被风完全吹起，船就会全速前进。这个表达源自航海术语，形容事情像顺风航行的船一样顺利。英语的「to be going full steam ahead」或「to be on a roll」意思相近。',
        'exercise_q': [
            {'question': '「Andare a gonfie vele」是什么意思？', 'options': ['Navigare con la barca', 'Andare bene, avere successo', 'Vendere vele', 'Andare al mare'], 'answer': 'B) Andare bene, avere successo'},
            {'question': 'Completa: Il progetto va a ________ __________, siamo molto contenti!', 'fill': ['gonfie, vele']},
        ],
        'english_eq': 'To be going smoothly / To be on a roll / Full steam ahead',
        'meaning_it_cn': '进展非常顺利，获得成功，一切顺利进行。',
    },

    {
        "id": 43,
        'idiom': 'Ingoiare il rospo',
        'category': 'Risentimento / Sottomissione',
        'meaning_cn': '忍气吞声 / 敢怒不敢言 / 含怒隐忍',
        'meaning_it': 'Rimangiarsi la rabbia, sopportare un\'offesa o un\'umiliazione senza reagire, accettare una situazione negativa senza protestare.',
        'usage_cn': '形容被迫吞下苦果、忍受屈辱却不能反抗的状态。常用于描述在工作或生活中被人欺负却只能默默忍受的情况。',
        'examples': [
            ('A', 'Il capo ti ha urlato addosso davanti a tutti? E tu cosa hai fatto?', '老板当众对你大吼大叫？你怎么做的？'),
            ('B', 'Ho dovuto ingoiare il rospo. Non potevo rispondere, ho bisogno di questo lavoro.', '我只能忍气吞声。我不能回嘴，我还需要这份工作。'),
            ('A1', 'Marco mi ha preso in giro davanti a tutti, ma non ho detto nulla.', 'Marco当众取笑我，但我什么都没说。'),
            ('B1', 'Hai ingoiato il rospo? Sei stato molto paziente!', '你忍气吞声了？你真是太能忍了！')
        ],
        'cultural_cn': '「Ingoiare = 吞下」「il rospo = 蟾蜍/癞蛤蟆」。字面意思是「吞下癞蛤蟆」。这个表达想想就让人不舒服——蛤蟆有毒不说，还又丑又难吃。但为了大局，有时不得不吞下去。这和中文的「打落牙齿和血吞」、「忍气吞声」表达的是同一个意思。英语的「to swallow one\'s pride / to eat humble pie」意思相近。',
        'exercise_q': [
            {'question': '「Ingoiare il rospo」是什么意思？', 'options': ['Mangiare un rospo vero', 'Sopportare un\'offesa senza reagire', 'Essere arrabbiati con qualcuno', 'Avere fame'], 'answer': 'B) Sopportare un\'offesa senza reagire'},
            {'question': 'Completa: Oggi il capo mi ha criticato, ma ho dovuto ________ il ________.', 'fill': ['ingoiare, rospo']},
        ],
        'english_eq': 'To swallow one\'s pride / To eat humble pie / To grin and bear it',
        'meaning_it_cn': '忍气吞声，咽下苦果，含怒隐忍。',
    },

    {
        "id": 44,
        'idiom': 'Essere a pezzi',
        'category': 'Dolore / Stanchezza',
        'meaning_cn': '心碎 / 身心俱疲 / 悲痛欲绝',
        'meaning_it': 'Provare un dolore profondo, essere emotivamente distrutti, sentirsi completamente spezzati.',
        'usage_cn': '形容极度伤心、悲痛欲绝的状态。也指身心俱疲、累到散架。',
        'examples': [
            ('A', 'Quando ha saputo della morte di suo padre, era a pezzi.', '当他得知父亲去世的消息时，他整个人都碎了。'),
            ('B', 'Poverino, era distrutto dal dolore.', '太可怜了，他悲痛欲绝。'),
            ('A1', 'Dopo la maratona di ieri sono a pezzi.', '跑完昨天的马拉松后，我整个人都散了。'),
            ('B1', 'Vai a riposarti, sei proprio a pezzi!', '快去休息吧，你累成什么样了！')
        ],
        'cultural_cn': '「Essere = 是」「a pezzi = 成碎片」。字面意思是「成了碎片」。这个表达用来形容人极度伤心或疲惫时，感觉自己像碎成一片片的一样。中文里「心碎」、「身心俱疲」传达的是类似的意思。英语的「to be torn apart」或「to be shattered」意思相近。',
        'exercise_q': [
            {'question': '「Essere a pezzi」可以形容什么状态？', 'options': ['Essere felici e contenti', 'Provare dolore profondo o stanchezza estrema', 'Avere molti pezzi di qualcosa', 'Essere in forma'], 'answer': 'B) Provare dolore profondo o stanchezza estrema'},
            {'question': 'Completa: Dopo quella notizia, ero proprio ____ ____.', 'fill': ['a, pezzi']},
        ],
        'english_eq': 'To be heartbroken / To be shattered / To be worn out',
        'meaning_it_cn': '极度心痛、身心俱疲、感觉整个人都散了。',
    },

    {
        "id": 45,
        'idiom': 'Avere le mani in pasta',
        'category': 'Influenza / Potere',
        'meaning_cn': '参与其中 / 插手某事 / 有关系有门路',
        'meaning_it': 'Essere coinvolto direttamente in un\'attività o in un affare, avere contatti e influenza in un determinato ambito.',
        'usage_cn': '形容某人参与了某个事务、有门路有关系。可用于商业、政治或个人事务，表达有能力在其中施加影响。',
        'examples': [
            ('A', 'Come hai fatto a ottenere quel contratto?', '你是怎么拿到那个合同的？'),
            ('B', 'Ho le mani in pasta in quel settore da anni!', '我在那个行业已经掺和了好多年了！'),
            ('A1', 'Marco ha sempre le mani in pasta negli affari del comune.', 'Marco在市政府的事务中总有他的关系。'),
            ('B1', 'Sì, conosce tutti gli assessori.', '是啊，他认识所有议员。')
        ],
        'cultural_cn': '「Avere = 有」「le mani = 手」「in pasta = 在面团里」。字面意思是「双手在面团里揉着」。这个表达来自意大利传统家庭厨房——揉面做面包或意面的场景。如果一个人手在面团里，说明他在参与制作，而不是旁观者。引申为在某个事务中有参与、有人脉、能施加影响。可中性使用，有时也带「插了一手」的微妙含义。英语类似表达「to have a finger in the pie」。',
        'exercise_q': [
            {'question': '「Avere le mani in pasta」的字面意思是什么？', 'options': ['手在面团里', '手在面条里', '手在肉里', '手在鱼里'], 'answer': 'A) 手在面团里'},
            {'question': 'Completa: Lui ________ sempre le ________ in ________ negli ________ del quartiere.', 'fill': ['ha, mani, pasta, affari']},
        ],
        'english_eq': 'To have a finger in the pie / To have a hand in something / To be in on something',
        'meaning_it_cn': '直接参与某个活动或事务，在某个领域有关系和影响力。',
    },

    {
        "id": 46,
        'idiom': 'Fare il passo più lungo della gamba',
        'category': 'Strategia / Azione',
        'meaning_cn': '做超过能力的事 / 贪多嚼不烂 / 力不从心',
        'meaning_it': 'Tentare di fare qualcosa che supera le proprie capacità, sopravvalutare le proprie forze.',
        'usage_cn': '形容试图做超过自己能力范围的事，贪多嚼不烂。也可指步子迈得太大，扯着蛋。',
        'examples': [
            ('A', 'Ho deciso di imparare tre lingue in un mese.', '我决定一个月学三门语言。'),
            ('B', 'Stai facendo il passo più lungo della gamba!', '你这是贪多嚼不烂啊！'),
            ('A1', 'Il progetto è troppo grande, stiamo facendo il passo più lungo della gamba.', '这个项目太大了，我们这是在做超过能力的事。'),
            ('B1', 'Dovremmo dividerlo in fasi più piccole.', '我们应该把它分成更小的阶段。')
        ],
        'cultural_cn': '「Fare = 做」「il passo = 步子」「più lungo = 更长」「della gamba = 比腿」。字面意思是「迈的步子比腿还长」。中文里「贪多嚼不烂」、「步子迈得太大」是类似表达。英语的「to bite off more than you can chew」或「to overreach」意思相近。',
        'exercise_q': [
            {'question': '这个习语和哪个中文表达最接近？', 'options': ['贪多嚼不烂', '画蛇添足', '井底之蛙', '塞翁失马'], 'answer': 'A) 贪多嚼不烂'},
            {'question': 'Completa: Stai facendo il ________ più ________ della ________!', 'fill': ['passo, lungo, gamba']},
        ],
        'english_eq': 'To bite off more than you can chew / To overreach / To punch above one\'s weight',
        'meaning_it_cn': '试图做超过自己能力范围的事，贪多嚼不烂。',
    },

    {
        "id": 47,
        'idiom': 'Mettere il carro davanti ai buoi',
        'category': 'Logica / Ordine',
        'meaning_cn': '本末倒置 / 把马车放在牛前面 / 顺序颠倒',
        'meaning_it': 'Agire in modo prematuro, facendo le cose nell\'ordine sbagliato, senza rispettare la logica naturale.',
        'usage_cn': '形容做事情不按正确顺序，先做后面的事再做前面的事，或在还没具备条件时就急着行动。和中文的「本末倒置」、「因果颠倒」以及英语的「put the cart before the horse」完全对应。',
        'examples': [
            ('A', 'Ho comprato la macchina nuova prima di trovare un lavoro!', '我还没找到工作就先买了新车！'),
            ('B', 'Ma stai mettendo il carro davanti ai buoi!', '你这是本末倒置啊！'),
            ('A1', 'Dobbiamo fare il business plan prima di aprire l\'azienda, non dopo!', '我们应该先做商业计划再开公司，而不是之后！'),
            ('B1', 'Hai ragione, stavamo mettendo il carro davanti ai buoi.', '你说得对，我们之前本末倒置了。')
        ],
        'cultural_cn': '「Mettere = 放」「il carro = 马车」「davanti = 前面」「ai buoi = 给牛」。字面意思是「把马车放在牛前面」。正常顺序是牛拉车（牛在前），但把车放在牛前面显然违反常理。中文「本末倒置」、英语「to put the cart before the horse」、法语「mettre la charrue avant les bœufs」都是同一个意思，跨语言完全对应。',
        'exercise_q': [
            {'question': '这个习语和哪个中文表达最接近？', 'options': ['本末倒置', '画蛇添足', '亡羊补牢', '得过且过'], 'answer': 'A) 本末倒置'},
            {'question': 'Completa: Stai mettendo il ________ davanti ai ________!', 'fill': ['carro, buoi']},
        ],
        'english_eq': 'To put the cart before the horse',
        'meaning_it_cn': '做事顺序颠倒，在逻辑上本末倒置，还没准备好就急着行动。',
    },
    {
        "id": 48,
        'idiom': 'Essere una mosca bianca',
        'category': 'Rarità / Unicità',
        'meaning_cn': '罕见的人或物 / 凤毛麟角 / 稀有之物',
        'meaning_it': 'Essere una persona o una cosa molto rara, difficile da trovare.',
        'usage_cn': '形容极其罕见、与众不同的人或事物。就像自然界中白色的苍蝇极其少见一样。用于强调某人/某物的稀缺性和独特性。',
        'examples': [
            ('A', 'Marco parla cinque lingue perfettamente. È una mosca bianca!', 'Marco精通五门语言。他简直是凤毛麟角！'),
            ('B', 'Hai ragione, è davvero raro trovare qualcuno così talentuoso.', '你说得对，找到这么有才华的人确实很少见。'),
            ('A1', 'In questa azienda, un capo che ascolta i dipendenti è una mosca bianca.', '在这家公司，愿意听取员工意见的老板真是凤毛麟角。'),
            ('B1', 'Infatti, di solito pensano solo ai profitti.', '没错，他们通常只考虑利润。'),
        ],
        'cultural_cn': '「Essere = 是」「una mosca = 一只苍蝇」「bianca = 白色的」。字面意思是「是一只白苍蝇」。在自然界中，普通苍蝇是黑色的，白色苍蝇极为罕见。这个表达借用了自然界的稀有现象来形容人或事物的独特性。中文的「凤毛麟角」、英语的「to be a rare bird」或「to be as rare as hen\'s teeth」表达了类似的意思。',
        'exercise_q': [
            {'question': '「Essere una mosca bianca」形容什么样的人？', 'options': ['Una persona molto comune', 'Una persona rara e speciale', 'Una persona che ama gli insetti', 'Una persona che ha paura delle mosche'], 'answer': 'B) Una persona rara e speciale'},
            {'question': 'Completa: In questo campo, un esperto vero è una ________ ________.', 'fill': ['mosca, bianca']},
        ],
        'english_eq': 'To be a rare bird / To be one in a million / To be as rare as hen\'s teeth',
        'meaning_it_cn': '是非常罕见的人或事物，极难找到。',
    },
    {
        "id": 49,
        'idiom': 'Costare un occhio della testa',
        'category': 'Economia / Valore',
        'meaning_cn': '贵得离谱 / 贵到肉疼 / 花大价钱',
        'meaning_it': 'Avere un prezzo esageratamente alto, troppo costoso.',
        'usage_cn': '形容某样东西价格极高，贵到让人心疼。指非常贵的东西。',
        'examples': [
            ('A', 'Quanto costa quel telefono nuovo?', '那个新手机多少钱？'),
            ('B', 'Costa un occhio della testa! 2000 euro!', '贵得离谱！2000欧元！'),
            ('A1', 'Il vacanza alle Maldive quest\'anno?', '今年去马尔代夫度假怎么样？'),
            ('B1', 'Costa un occhio della testa, altrimenti non andiamo.', '贵死了，不然我们就不去了。')
        ],
        'cultural_cn': '「Costare = 花费」「un occhio = 一只眼睛」「della testa = 脑袋的」。字面意思是「花掉脑袋上的一只眼睛」。这个表达来自意大利传统——眼睛是心灵的窗户，最珍贵的东西。如果有人说为了买某个东西愿意捐一只眼睛，说明这个东西贵得让人肝疼。中文的「倾家荡产」、英语的「to cost an arm and a leg」是类似表达。',
        'exercise_q': [
            {'question': '「Costare un occhio della testa」是什么意思？', 'options': [' Gratis', 'Molto costoso', 'A buon mercato', 'Non vale nulla'], 'answer': 'B) Molto costoso'},
            {'question': 'Completa: Quel telefono ____ un ________ della ________!', 'fill': ['costa', 'occhio', 'testa']},
        ],
        'english_eq': 'To cost an arm and a leg / To cost a fortune / To break the bank',
        'meaning_it_cn': '价格极高，贵得让人心疼。',
    },
    {
        "id": 50,
        'idiom': 'Parlare a vanvera',
        'category': 'Comunicazione / Chiacchiere',
        'meaning_cn': '胡说八道 / 信口开河 / 瞎扯淡',
        'meaning_it': 'Dire cose senza senso, raccontare frottole, parlare senza pensare.',
        'usage_cn': '形容人说话不经过大脑，胡说八道。也可指吹牛、夸大其词。',
        'examples': [
            ('A', 'Hai sentito cosa ha detto Marco?', '你听说Marco说什么了吗？'),
            ('B', 'Sì, ma parla a vanvera come sempre!', '是啊，但他总是胡说八道！'),
            ('A1', 'Il nuovo progetto sarà pronto domani!', '新项目明天就能完成！'),
            ('B1', 'Ma parli a vanvera, non è vero!', '你少瞎吹了，不可能！')
        ],
        'cultural_cn': '「Parlare = 说话」「a vanvera = 胡乱地」。vanvera 来自威尼斯方言「vanera」，意思是「假的、空的」。字面意思是「空着说话」——没内容、没根据，就是瞎扯。中文的「胡说八道」、「信口开河」是类似表达。英语的「to talk nonsense」或「to shoot the breeze」。',
        'exercise_q': [
            {'question': '「Parlare a vanvera」是什么意思？', 'options': ['Parlare seriamente', 'Dire bugie o assurdità', 'Tacere', 'Parlare piano'], 'answer': 'B) Dire bugie o assurdità'},
            {'question': 'Completa: Non ascoltarlo, lui ____ a ________.', 'fill': ['parla', 'vanvera']},
        ],
        'english_eq': 'To talk nonsense / To shoot the breeze / To blow hot air',
        'meaning_it_cn': '说些没意义的话，胡说八道、瞎扯淡。',
    },
]